[platformio]
default_envs = edgehax_s3_pro_diagnostics
src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib
test_dir = firmware/test
data_dir = firmware/data

[env:edgehax_s3_pro_diagnostics]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_port = COM7
monitor_port = COM7
monitor_speed = 115200
upload_speed = 115200

board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

lib_deps =
  zinggjm/GxEPD2@^1.6.9

build_flags =
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_CDC_ON_BOOT=0
